// -*- C++ -*- generated by wxGlade 0.3.1 on Wed Sep 29 16:09:00 2004
/*
 * Copyright (C) 2008 Vaclav Peroutka <vaclavpe@seznam.cz>
 *
 * Licensed under the GNU General Public License Version 2
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <https://www.gnu.org/licenses/>.
 */

#include "AudMeS.h"

#include <math.h>
#include <wx/dcmemory.h>
#include <wx/filename.h>
#include <wx/stdpaths.h>

#ifdef __WXMSW__
#include <windows.h>
#endif
#include <libfccp/csv.h>

#include <atomic>
#include <fstream>
#include <iostream>

#include "dlg_audiointerface.h"
#include "event_ids.h"
#include "fourier.h"

wxIMPLEMENT_CLASS(MainFrame, wxFrame);

wxBEGIN_EVENT_TABLE(MainFrame, wxFrame)
  EVT_TOGGLEBUTTON(ID_SPESTART, MainFrame::OnSpanStart)
  EVT_TOGGLEBUTTON(ID_GENSTART, MainFrame::OnGenStart)
  EVT_TOGGLEBUTTON(ID_OSCSTART, MainFrame::OnOscStart)
  EVT_TOGGLEBUTTON(ID_FRMSTART, MainFrame::OnFrmStart)
  EVT_MENU(wxID_ABOUT, MainFrame::OnAboutClick)
  EVT_MENU(wxID_EXIT, MainFrame::OnExitClick)
  EVT_CLOSE(MainFrame::OnClose)
  EVT_MENU(ID_SNDCARD, MainFrame::OnSelectSndCard)
  EVT_TIMER(ID_TIMERID, MainFrame::OnTimer)
  EVT_CHECKBOX(ID_GENLENB, MainFrame::OnGeneratorChanged)
  EVT_CHECKBOX(ID_GENRENB, MainFrame::OnGeneratorChanged)
  EVT_CHECKBOX(ID_GENSYNC, MainFrame::OnGeneratorChanged)
  EVT_TEXT_ENTER(ID_GENPHASE, MainFrame::OnGeneratorChanged)
  EVT_COMMAND_SCROLL(ID_GENLFREQ, MainFrame::OnGenScrollLChanged)
  EVT_COMMAND_SCROLL(ID_GENRFREQ, MainFrame::OnGenScrollRChanged)
  EVT_COMMAND_SCROLL(ID_GENLAMP, MainFrame::OnGenScrollChanged)
  EVT_COMMAND_SCROLL(ID_GENRAMP, MainFrame::OnGenScrollChanged)
  EVT_CHOICE(ID_OSCTRIG, MainFrame::OnOscChoiceChanged)
  EVT_COMMAND_SCROLL(ID_OSCLEVEL, MainFrame::OnOscScrollChanged)
  EVT_TEXT_ENTER(ID_TXT_FREQ_L, MainFrame::OnTxtFreqLChanged)
  EVT_TEXT_ENTER(ID_TXT_FREQ_R, MainFrame::OnTxtFreqRChanged)
  EVT_CHOICE(ID_GENSHP_L, MainFrame::OnGeneratorChanged)
  EVT_CHOICE(ID_GENSHP_R, MainFrame::OnGeneratorChanged)
  EVT_MENU(wxID_OPEN, MainFrame::OnOpenClick)
  EVT_MENU(wxID_SAVE, MainFrame::OnSaveClick)
  EVT_MENU(wxID_SAVEAS, MainFrame::OnSaveAsClick)
  EVT_MENU(ID_LOAD_FRM, MainFrame::OnLoadFRM)
  EVT_MENU(ID_SAVE_FRM, MainFrame::OnSaveFRM)
  EVT_MENU(ID_SAVE_SPE, MainFrame::OnSaveSPE)
  EVT_MENU(ID_SAVE_OSC, MainFrame::OnSaveOSC)
  EVT_BUTTON(ID_AUTOCAL, MainFrame::OnAutoCalClick)
  EVT_TOGGLEBUTTON(ID_SINC, MainFrame::OnSincClick)
  EVT_CHOICE(ID_XSCALE, MainFrame::OnXScaleChanged)
  EVT_CHOICE(ID_FFTAVG, MainFrame::OnFFTAvgChanged)
  EVT_CHOICE(ID_FFTREF, MainFrame::OnFFTScaleChanged)
  EVT_CHOICE(ID_FFTDBDIV, MainFrame::OnFFTScaleChanged)
  EVT_BUTTON(ID_SA_START, MainFrame::OnSAStart)
  EVT_BUTTON(ID_SA_PREV, MainFrame::OnSAPrev)
  EVT_BUTTON(ID_SA_NEXT, MainFrame::OnSANext)
  EVT_BUTTON(ID_SA_REPEAT, MainFrame::OnSARepeat)
  EVT_BUTTON(ID_SA_AUDIO_SETUP, MainFrame::OnSAAudioSetup)
  EVT_BUTTON(ID_DEVICE_REFRESH, MainFrame::OnDeviceRefresh)
wxEND_EVENT_TABLE()

float* g_OscBuffer_Left;
float* g_OscBuffer_Right;
long int g_OscBufferPosition;

float* g_SpeBuffer_Left;
float* g_SpeBuffer_Right;
long int g_SpeBufferPosition;

std::atomic<bool> g_OscBufferChanged{false};
std::atomic<bool> g_SpeBufferChanged{false};

///////////////////////////////////////////////////////////////////////
MainFrame::MainFrame(wxWindow* parent, int id, const wxString& title, const wxPoint& pos,
                     const wxSize& size, long WXUNUSED(style))
    : wxFrame(parent, id, title, pos, size, wxDEFAULT_FRAME_STYLE | wxFULL_REPAINT_ON_RESIZE) {
  // begin wxGlade: MainFrame::MainFrame
  notebook_1 = new wxNotebook(this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxNB_TOP);
  notebook_1_home = new wxPanel(notebook_1, -1);
  notebook_1_sa = new wxPanel(notebook_1, -1);
  notebook_1_spe = new wxPanel(notebook_1, -1);
  notebook_1_osc = new wxPanel(notebook_1, -1);
  notebook_1_gen = new wxPanel(notebook_1, -1);
  notebook_1_frm = new wxPanel(notebook_1, -1);
  sizer_gen_l_staticbox = new wxStaticBox(notebook_1_gen, wxID_ANY, wxT("Left channel"));
  sizer_gen_r_staticbox = new wxStaticBox(notebook_1_gen, wxID_ANY, wxT("Right channel"));
  sizer_osc_l_staticbox = new wxStaticBox(notebook_1_osc, wxID_ANY, wxT("Vertical Left"));
  sizer_osc_r_staticbox = new wxStaticBox(notebook_1_osc, wxID_ANY, wxT("Vertical Right"));
  sizer_osc_h_staticbox = new wxStaticBox(notebook_1_osc, wxID_ANY, wxT("Horizontal"));
  sizer_spe_fft_staticbox = new wxStaticBox(notebook_1_spe, wxID_ANY, wxT("FFT 分析"));
  sizer_spe_disp_staticbox = new wxStaticBox(notebook_1_spe, wxID_ANY, wxT("频段"));
  sizer_spe_scale_staticbox = new wxStaticBox(notebook_1_spe, wxID_ANY, wxT("显示量程"));
  sizer_frm_prop_staticbox = new wxStaticBox(notebook_1_frm, wxID_ANY, wxT("扫频设置"));
  frame_1_menubar = new wxMenuBar();
  wxMenu* wxglade_tmp_menu_1 = new wxMenu();
  wxglade_tmp_menu_1->Append(wxID_OPEN, wxT("打开配置...\tAlt+O"), wxT(""), wxITEM_NORMAL);
  wxglade_tmp_menu_1->Append(wxID_SAVE, wxT("保存配置...\tAlt+S"), wxT(""), wxITEM_NORMAL);
  wxglade_tmp_menu_1->Append(wxID_SAVEAS, wxT("另存为"), wxT(""), wxITEM_NORMAL);
  wxglade_tmp_menu_1->Append(ID_LOAD_FRM, wxT("载入扫频数据"), wxT(""), wxITEM_NORMAL);
  wxglade_tmp_menu_1->Append(ID_SAVE_FRM, wxT("保存扫频数据"), wxT(""), wxITEM_NORMAL);
  wxglade_tmp_menu_1->Append(ID_SAVE_SPE, wxT("保存 FFT 数据"), wxT(""), wxITEM_NORMAL);
  wxglade_tmp_menu_1->Append(ID_SAVE_OSC, wxT("保存波形数据"), wxT(""), wxITEM_NORMAL);
  wxglade_tmp_menu_1->AppendSeparator();
  wxglade_tmp_menu_1->Append(wxID_EXIT, wxT("退出\tAlt+F4"), wxT(""), wxITEM_NORMAL);
  frame_1_menubar->Append(wxglade_tmp_menu_1, wxT("文件"));
  wxMenu* wxglade_tmp_menu_2 = new wxMenu();
  wxglade_tmp_menu_2->Append(ID_SNDCARD, wxT("音频接口设置..."), wxT(""),
                             wxITEM_NORMAL);
  frame_1_menubar->Append(wxglade_tmp_menu_2, wxT("工具"));
  wxMenu* wxglade_tmp_menu_3 = new wxMenu();
  wxglade_tmp_menu_3->Append(wxID_ABOUT, wxT("关于..."), wxT(""), wxITEM_NORMAL);
  frame_1_menubar->Append(wxglade_tmp_menu_3, wxT("帮助"));
  SetMenuBar(frame_1_menubar);

  frame_1_statusbar = CreateStatusBar(1, 0);

  /* generator panel */
  checkbox_l_en = new wxCheckBox(notebook_1_gen, ID_GENLENB, wxT("Enable Output"));
  label_gen_wave_l = new wxStaticText(notebook_1_gen, wxID_ANY, wxT("Waveform: "));
  const wxString choice_l_wav_choices[] = {wxT("Sine"),     wxT("Rectangular"), wxT("Saw"),
                                           wxT("Triangle"), wxT("Wh-Noise"),    wxT("Wobble")};
  choice_l_wav = new wxChoice(notebook_1_gen, ID_GENSHP_L, wxDefaultPosition, wxDefaultSize, 6,
                              choice_l_wav_choices, 0);
  label__gen_freq_l = new wxStaticText(notebook_1_gen, wxID_ANY, wxT("Frequency [20..20000Hz]: "));
  slide_l_fr = new wxSlider(notebook_1_gen, ID_GENLFREQ, 80, 0, 200);
  label_gen_ampl_l = new wxStaticText(notebook_1_gen, -1, wxT("Amplitude [0..-60dB]: "));
  slide_l_am = new wxSlider(notebook_1_gen, ID_GENLAMP, 0, -60, 0);

  checkbox_r_en = new wxCheckBox(notebook_1_gen, ID_GENRENB, wxT("Enable Output"));
  label_gen_wave_r = new wxStaticText(notebook_1_gen, wxID_ANY, wxT("Waveform: "));
  const wxString choice_r_wav_choices[] = {wxT("Sine"),     wxT("Rectangular"), wxT("Saw"),
                                           wxT("Triangle"), wxT("Wh-Noise"),    wxT("Wobble")};
  choice_r_wav = new wxChoice(notebook_1_gen, ID_GENSHP_R, wxDefaultPosition, wxDefaultSize, 6,
                              choice_r_wav_choices, 0);
  label_gen_freq_r = new wxStaticText(notebook_1_gen, wxID_ANY, wxT("Frequency [20..20000Hz]: "));
  slide_r_fr = new wxSlider(notebook_1_gen, ID_GENRFREQ, 80, 0, 200);
  label_gen_ampl_r = new wxStaticText(notebook_1_gen, -1, wxT("Amplitude [0..-60dB]: "));
  slide_r_am = new wxSlider(notebook_1_gen, ID_GENRAMP, 0, -60, 0);
  button_gen_start = new wxToggleButton(notebook_1_gen, ID_GENSTART, wxT("Start"));

  checkbox_gen_sync = new wxCheckBox(notebook_1_gen, ID_GENSYNC, wxT("L and R are synchronized"));
  label_gen_sync =
      new wxStaticText(notebook_1_gen, wxID_ANY, wxT("Phase between L and R [0..360 degrees]: "));
  text_gen_sync = new wxTextCtrl(notebook_1_gen, ID_GENPHASE, wxT("0"), wxDefaultPosition,
                                 wxDefaultSize, wxTE_PROCESS_ENTER);

  txt_freq_l = new wxTextCtrl(notebook_1_gen, ID_TXT_FREQ_L, wxT("  315.0"), wxDefaultPosition,
                              wxDefaultSize, wxTE_PROCESS_ENTER);
  txt_freq_r = new wxTextCtrl(notebook_1_gen, ID_TXT_FREQ_R, wxT("  315.0"), wxDefaultPosition,
                              wxDefaultSize, wxTE_PROCESS_ENTER);

  /* oscilloscope panel */
  window_osc = new CtrlOScope(notebook_1_osc, _T(""), _T(""));
  label_osc_div_l = new wxStaticText(notebook_1_osc, wxID_ANY, wxT("[V/div]: "));
  const wxString choice_osc_l_res_choices[] = {
      wxT("0.2"), wxT("0.1"),  wxT("50m"),  wxT("20m"),  wxT("10m"), wxT("5m"),  wxT("2m"),
      wxT("1m"),  wxT("500u"), wxT("200u"), wxT("100u"), wxT("50u"), wxT("20u"), wxT("10u"),
  };
  choice_osc_l_res = new wxChoice(notebook_1_osc, ID_XSCALE, wxDefaultPosition, wxDefaultSize, 14,
                                  choice_osc_l_res_choices, 0);
  label_osc_off_l = new wxStaticText(notebook_1_osc, wxID_ANY, wxT("Offset: "));
  const wxString choice_osc_l_off_choices[] = {wxT("1"),    wxT("0.8"),  wxT("0.6"),  wxT("0.4"),
                                               wxT("0.2"),  wxT("0"),    wxT("-0.2"), wxT("-0.4"),
                                               wxT("-0.6"), wxT("-0.8"), wxT("-1")};
  choice_osc_l_off = new wxChoice(notebook_1_osc, ID_XSCALE, wxDefaultPosition, wxDefaultSize, 11,
                                  choice_osc_l_off_choices, 0);

  label_osc_div_r = new wxStaticText(notebook_1_osc, wxID_ANY, wxT("[V/div]: "));
  const wxString choice_osc_r_res_choices[] = {
      wxT("0.2"), wxT("0.1"),  wxT("50m"),  wxT("20m"),  wxT("10m"), wxT("5m"),  wxT("2m"),
      wxT("1m"),  wxT("500u"), wxT("200u"), wxT("100u"), wxT("50u"), wxT("20u"), wxT("10u"),
  };
  choice_osc_r_res = new wxChoice(notebook_1_osc, ID_XSCALE, wxDefaultPosition, wxDefaultSize, 14,
                                  choice_osc_r_res_choices, 0);
  label_osc_off_r = new wxStaticText(notebook_1_osc, wxID_ANY, wxT("Offset: "));
  const wxString choice_osc_r_off_choices[] = {wxT("1"),    wxT("0.8"),  wxT("0.6"),  wxT("0.4"),
                                               wxT("0.2"),  wxT("0"),    wxT("-0.2"), wxT("-0.4"),
                                               wxT("-0.6"), wxT("-0.8"), wxT("-1")};
  choice_osc_r_off = new wxChoice(notebook_1_osc, ID_XSCALE, wxDefaultPosition, wxDefaultSize, 11,
                                  choice_osc_r_off_choices, 0);

  button_autocalibrate = new wxButton(notebook_1_osc, ID_AUTOCAL, wxT("V Autorange"));
  button_sinc = new wxToggleButton(notebook_1_osc, ID_SINC, wxT("sin(x)/x"));

  const wxString choice_osc_swp_choices[] = {
      wxT("10"),   wxT("20"),   wxT("50"),   wxT("100"),   wxT("200"),   wxT("500"),
      wxT("1000"), wxT("2000"), wxT("5000"), wxT("10000"), wxT("20000"), wxT("50000"),
  };
  choice_osc_swp = new wxChoice(notebook_1_osc, ID_XSCALE, wxDefaultPosition, wxDefaultSize, 12,
                                choice_osc_swp_choices, 0);
  label_osc_time = new wxStaticText(notebook_1_osc, wxID_ANY, wxT("Time [us/div]: "));

  // trigger control
  label_osc_trig = new wxStaticText(notebook_1_osc, wxID_ANY, wxT("Trigger: "));
  const wxString choice_osc_trig_source_choices[] = {wxT("Off"), wxT("Ch 1"), wxT("Ch 2")};
  choice_osc_trig_source = new wxChoice(notebook_1_osc, ID_OSCTRIG, wxDefaultPosition,
                                        wxDefaultSize, 3, choice_osc_trig_source_choices, 0);
  const wxString choice_osc_trig_edge_choices[] = {wxT("Rising"), wxT("Falling")};
  choice_osc_trig_edge = new wxChoice(notebook_1_osc, ID_OSCTRIG, wxDefaultPosition, wxDefaultSize,
                                      2, choice_osc_trig_edge_choices, 0);
  label_osc_level = new wxStaticText(notebook_1_osc, wxID_ANY, wxT("Level [-1.0...+1.0]: 0.0"));
  slide_osc_level = new wxSlider(notebook_1_osc, ID_OSCLEVEL, 0, -10, +10);

  button_osc_start = new wxToggleButton(notebook_1_osc, ID_OSCSTART, wxT("Start"));

  /* Spectrum analyzer */
  label_5 = new wxStaticText(notebook_1_spe, wxID_ANY, wxT("窗函数"));
  const wxString choice_fft_choices[] = {wxT("Rect"), wxT("Hanning"), wxT("Blackman"),
                                         wxT("BlackHarr")};
  choice_fft = new wxChoice(notebook_1_spe, ID_FFTWINDOW, wxDefaultPosition, wxDefaultSize, 4,
                            choice_fft_choices, 0);

  label_9 = new wxStaticText(notebook_1_spe, wxID_ANY, wxT("FFT 点数"));
  const wxString choice_fftlength_choices[] = {wxT("128"),   wxT("256"),  wxT("512"),  wxT("1024"),
                                               wxT("2048"),  wxT("4096"), wxT("8192"), wxT("16384"),
                                               wxT("32768"), wxT("65536")};
  choice_fftlength = new wxChoice(notebook_1_spe, ID_XSCALE, wxDefaultPosition, wxDefaultSize, 10,
                                  choice_fftlength_choices, 0);

  label_rx = new wxStaticText(notebook_1_spe, wxID_ANY, wxT("频率范围 [Hz]"));
  const wxString choice_fftry_choices[] = {wxT("2-2000"), wxT("20-20k"), wxT("10-100k")};
  choice_fftrx = new wxChoice(notebook_1_spe, ID_FFTWINDOW, wxDefaultPosition, wxDefaultSize, 3,
                              choice_fftry_choices, 0);

  label_avg = new wxStaticText(notebook_1_spe, wxID_ANY, wxT("平均次数"));
  const wxString choice_fftavg_choices[] = {wxT("1"), wxT("2"), wxT("5"), wxT("10"), wxT("20")};
  choice_fftavg = new wxChoice(notebook_1_spe, ID_FFTAVG, wxDefaultPosition, wxDefaultSize, 5,
                               choice_fftavg_choices, 0);

  label_spe_ref = new wxStaticText(notebook_1_spe, wxID_ANY, wxT("参考电平 [dB]"));
  const wxString choice_spe_ref_choices[] = {wxT("0"),   wxT("-10"), wxT("-20"),
                                             wxT("-30"), wxT("-40"), wxT("-50")};
  choice_spe_ref = new wxChoice(notebook_1_spe, ID_FFTREF, wxDefaultPosition, wxDefaultSize, 6,
                                choice_spe_ref_choices, 0);

  label_spe_dbdiv = new wxStaticText(notebook_1_spe, wxID_ANY, wxT("幅度 [dB/div]"));
  const wxString choice_spe_dbdiv_choices[] = {wxT("3"), wxT("5"), wxT("10")};
  choice_spe_dbdiv = new wxChoice(notebook_1_spe, ID_FFTDBDIV, wxDefaultPosition, wxDefaultSize, 3,
                                  choice_spe_dbdiv_choices, 0);

  window_1_spe = new CtrlOScope(notebook_1_spe, _T("Hz"), _T("dB"));
  button_spe_start = new wxToggleButton(notebook_1_spe, ID_SPESTART, wxT("开始 FFT"));
  label_fft_freq_value = new wxStaticText(notebook_1_spe, wxID_ANY, wxT("基波  -- Hz"));
  label_fft_mag_value = new wxStaticText(notebook_1_spe, wxID_ANY, wxT("幅度  -- dBFS"));
  label_thd_value = new wxStaticText(notebook_1_spe, wxID_ANY, wxT("THD  -- %"));


  /* Frequency response */
  label_1_frm = new wxStaticText(notebook_1_frm, wxID_ANY, wxT("扫频点数（最大 120）"));
  text_ctrl1_frm = new wxTextCtrl(notebook_1_frm, wxID_ANY, wxT(" 24"));
  button_frm_start = new wxToggleButton(notebook_1_frm, ID_FRMSTART, wxT("开始扫频"));
  window_1_frm = new CtrlOScope(notebook_1_frm, _T("Hz"), _T("dB"));

  BuildInstrumentHome();
  BuildSA440F5Panel();
  set_properties();
  do_layout();
  // end wxGlade
  set_custom_props();
}

void MainFrame::set_properties() {
  // begin wxGlade: MainFrame::set_properties
  SetTitle(wxT("AudMeS 测试分析仪"));
  int frame_1_statusbar_widths[] = {-1};
  frame_1_statusbar->SetStatusWidths(1, frame_1_statusbar_widths);
  frame_1_statusbar->SetStatusText("AudMeS 测试分析仪  ·  FFT / THD / Sweep / SA-440F5");
  choice_l_wav->SetSelection(0);
  choice_r_wav->SetSelection(0);
  choice_osc_swp->SetSelection(6);
  choice_osc_l_res->SetSelection(0);
  choice_osc_l_off->SetSelection(5);
  choice_osc_trig_source->SetSelection(0);
  choice_osc_r_res->SetSelection(0);
  choice_osc_r_off->SetSelection(5);
  choice_osc_trig_edge->SetSelection(0);
  choice_fft->SetSelection(1);
  choice_fftlength->SetSelection(4);
  choice_fftrx->SetSelection(1);
  choice_fftavg->SetSelection(0);
  choice_spe_ref->SetSelection(0);
  choice_spe_dbdiv->SetSelection(2);
  // end wxGlade
}


void MainFrame::BuildInstrumentHome() {
  wxBoxSizer* root = new wxBoxSizer(wxVERTICAL);

  wxStaticText* title =
      new wxStaticText(notebook_1_home, wxID_ANY, wxT("AudMeS 测试分析仪"));
  wxFont titleFont = title->GetFont();
  titleFont.SetPointSize(titleFont.GetPointSize() + 8);
  titleFont.SetWeight(wxFONTWEIGHT_BOLD);
  title->SetFont(titleFont);
  root->Add(title, 0, wxLEFT | wxRIGHT | wxTOP, 24);

  wxStaticText* subtitle = new wxStaticText(
      notebook_1_home, wxID_ANY,
      wxT("面向低噪声前置放大器测试 · FFT / THD / Sweep / SA-440F5"));
  root->Add(subtitle, 0, wxLEFT | wxRIGHT | wxTOP | wxBOTTOM, 24);

  wxStaticBoxSizer* deviceBox =
      new wxStaticBoxSizer(wxVERTICAL, notebook_1_home, wxT("音频接口"));
  label_device_status =
      new wxStaticText(notebook_1_home, wxID_ANY, wxT("正在检测 TOPPING E4x4 Pre…"));
  wxFont statusFont = label_device_status->GetFont();
  statusFont.SetPointSize(statusFont.GetPointSize() + 3);
  statusFont.SetWeight(wxFONTWEIGHT_BOLD);
  label_device_status->SetFont(statusFont);
  label_device_detail =
      new wxStaticText(notebook_1_home, wxID_ANY, wxT("建议 Windows 使用 TOPPING 官方驱动 / ASIO"));
  button_device_refresh =
      new wxButton(notebook_1_home, ID_DEVICE_REFRESH, wxT("重新检测设备"));

  deviceBox->Add(label_device_status, 0, wxALL, 10);
  deviceBox->Add(label_device_detail, 0, wxLEFT | wxRIGHT | wxBOTTOM, 10);
  deviceBox->Add(button_device_refresh, 0, wxLEFT | wxRIGHT | wxBOTTOM, 10);
  root->Add(deviceBox, 0, wxLEFT | wxRIGHT | wxEXPAND, 24);

  wxStaticBoxSizer* workflowBox =
      new wxStaticBoxSizer(wxVERTICAL, notebook_1_home, wxT("推荐工作流"));
  label_home_hint = new wxStaticText(
      notebook_1_home, wxID_ANY,
      wxT("① FFT / THD：1 kHz 基波、谐波与底噪\n"
          "② Sweep：20 Hz–40 kHz 音频段幅频响应\n"
          "③ SA-440F5 一键测试：按接线 → Loopback → 增益 → Sweep → THD → Noise 的顺序执行\n\n"
          "Generator 与示波器功能仍保留在后台，供 Sweep 和自动测试调用。"));
  workflowBox->Add(label_home_hint, 1, wxALL | wxEXPAND, 12);
  root->Add(workflowBox, 1, wxLEFT | wxRIGHT | wxTOP | wxBOTTOM | wxEXPAND, 24);

  notebook_1_home->SetSizer(root);
}

wxBitmap MainFrame::MakeGuidePlaceholder(const wxString& title, const wxString& subtitle,
                                         const wxSize& size) {
  wxBitmap bitmap(size.x, size.y);
  wxMemoryDC dc(bitmap);
  dc.SetBackground(wxBrush(wxColour(22, 27, 34)));
  dc.Clear();
  dc.SetTextForeground(wxColour(235, 240, 245));
  dc.SetPen(wxPen(wxColour(70, 155, 210), 2));

  wxRect outer(12, 12, size.x - 24, size.y - 24);
  dc.DrawRoundedRectangle(outer, 10);

  wxFont head = wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT);
  head.SetPointSize(head.GetPointSize() + 3);
  head.SetWeight(wxFONTWEIGHT_BOLD);
  dc.SetFont(head);
  dc.DrawText(title, 30, 30);

  wxFont body = wxSystemSettings::GetFont(wxSYS_DEFAULT_GUI_FONT);
  body.SetPointSize(body.GetPointSize() + 1);
  dc.SetFont(body);
  dc.DrawText(subtitle, 30, 75);

  const int y = size.y / 2 + 10;
  const int boxW = (size.x - 120) / 3;
  wxRect a(30, y, boxW, 70);
  wxRect b(60 + boxW, y, boxW, 70);
  wxRect c(90 + boxW * 2, y, boxW, 70);
  dc.DrawRoundedRectangle(a, 8);
  dc.DrawRoundedRectangle(b, 8);
  dc.DrawRoundedRectangle(c, 8);
  dc.DrawText(wxT("E4x4 Pre"), a.x + 16, a.y + 24);
  dc.DrawText(wxT("SA-440F5"), b.x + 16, b.y + 24);
  dc.DrawText(wxT("FFT / THD"), c.x + 16, c.y + 24);
  dc.DrawLine(a.GetRight(), a.y + a.height / 2, b.x, b.y + b.height / 2);
  dc.DrawLine(b.GetRight(), b.y + b.height / 2, c.x, c.y + c.height / 2);
  dc.SelectObject(wxNullBitmap);
  return bitmap;
}

void MainFrame::BuildSA440F5Panel() {
  m_saStep = 0;
  wxBoxSizer* root = new wxBoxSizer(wxVERTICAL);

  wxBoxSizer* top = new wxBoxSizer(wxHORIZONTAL);
  wxStaticText* title =
      new wxStaticText(notebook_1_sa, wxID_ANY, wxT("SA-440F5 一键测试向导"));
  wxFont titleFont = title->GetFont();
  titleFont.SetPointSize(titleFont.GetPointSize() + 6);
  titleFont.SetWeight(wxFONTWEIGHT_BOLD);
  title->SetFont(titleFont);
  button_sa_start = new wxButton(notebook_1_sa, ID_SA_START, wxT("一键开始测试"));
  button_sa_audio_setup = new wxButton(notebook_1_sa, ID_SA_AUDIO_SETUP, wxT("音频接口设置"));
  top->Add(title, 1, wxALIGN_CENTER_VERTICAL | wxRIGHT, 12);
  top->Add(button_sa_audio_setup, 0, wxALIGN_CENTER_VERTICAL | wxRIGHT, 8);
  top->Add(button_sa_start, 0, wxALIGN_CENTER_VERTICAL);
  root->Add(top, 0, wxALL | wxEXPAND, 20);

  gauge_sa_progress = new wxGauge(notebook_1_sa, wxID_ANY, 7);
  root->Add(gauge_sa_progress, 0, wxLEFT | wxRIGHT | wxBOTTOM | wxEXPAND, 20);

  wxBoxSizer* main = new wxBoxSizer(wxHORIZONTAL);
  wxBoxSizer* left = new wxBoxSizer(wxVERTICAL);
  label_sa_step_counter =
      new wxStaticText(notebook_1_sa, wxID_ANY, wxT("步骤 1 / 7"));
  label_sa_step_title =
      new wxStaticText(notebook_1_sa, wxID_ANY, wxT("设备与安全检查"));
  wxFont stepFont = label_sa_step_title->GetFont();
  stepFont.SetPointSize(stepFont.GetPointSize() + 4);
  stepFont.SetWeight(wxFONTWEIGHT_BOLD);
  label_sa_step_title->SetFont(stepFont);

  label_sa_step_body =
      new wxStaticText(notebook_1_sa, wxID_ANY, wxEmptyString, wxDefaultPosition,
                       wxSize(430, -1), wxST_NO_AUTORESIZE);
  label_sa_step_body->Wrap(420);
  left->Add(label_sa_step_counter, 0, wxBOTTOM, 8);
  left->Add(label_sa_step_title, 0, wxBOTTOM, 12);
  left->Add(label_sa_step_body, 1, wxEXPAND);

  bitmap_sa_guide =
      new wxStaticBitmap(notebook_1_sa, wxID_ANY,
                         MakeGuidePlaceholder(wxT("测试指导"), wxT("等待开始"), wxSize(620, 360)));
  main->Add(left, 0, wxALL | wxEXPAND, 12);
  main->Add(bitmap_sa_guide, 1, wxALL | wxEXPAND, 12);
  root->Add(main, 1, wxLEFT | wxRIGHT | wxEXPAND, 8);

  wxBoxSizer* nav = new wxBoxSizer(wxHORIZONTAL);
  button_sa_prev = new wxButton(notebook_1_sa, ID_SA_PREV, wxT("上一步"));
  button_sa_repeat = new wxButton(notebook_1_sa, ID_SA_REPEAT, wxT("重新生成本步引导"));
  button_sa_next = new wxButton(notebook_1_sa, ID_SA_NEXT, wxT("下一步"));
  nav->Add(button_sa_prev, 0, wxRIGHT, 8);
  nav->Add(button_sa_repeat, 0, wxRIGHT, 8);
  nav->AddStretchSpacer(1);
  nav->Add(button_sa_next, 0);
  root->Add(nav, 0, wxALL | wxEXPAND, 20);

  notebook_1_sa->SetSizer(root);
  UpdateSA440F5Step();
}

void MainFrame::ApplyInstrumentTheme(wxWindow* root) {
  if (!root) return;
  const wxColour panel(24, 29, 36);
  const wxColour text(232, 238, 244);
  const wxColour accent(63, 169, 225);

  if (dynamic_cast<wxPanel*>(root) || root == this) root->SetBackgroundColour(panel);
  if (wxStaticText* st = dynamic_cast<wxStaticText*>(root)) st->SetForegroundColour(text);
  if (wxButton* bt = dynamic_cast<wxButton*>(root)) {
    bt->SetForegroundColour(text);
    bt->SetBackgroundColour(wxColour(42, 52, 64));
  }
  if (wxToggleButton* bt = dynamic_cast<wxToggleButton*>(root)) {
    bt->SetForegroundColour(text);
    bt->SetBackgroundColour(wxColour(42, 52, 64));
  }
  if (wxGauge* gauge = dynamic_cast<wxGauge*>(root)) {
    gauge->SetForegroundColour(accent);
  }

  for (wxWindowList::compatibility_iterator node = root->GetChildren().GetFirst(); node;
       node = node->GetNext()) {
    ApplyInstrumentTheme(node->GetData());
  }
}

void MainFrame::UpdateSA440F5Step() {
  struct Step {
    const wxChar* title;
    const wxChar* body;
    const wxChar* guide;
  };
  static const Step steps[] = {
      {wxT("设备与安全检查"),
       wxT("确认 TOPPING E4x4 Pre 已连接并被软件识别。\n"
           "48 V 幻象电源必须关闭。先不要连接 SA-440F5 输出到高增益输入。\n"
           "推荐采样率 96 kHz；正式测量前先完成 Loopback 基准。"),
       wxT("E4x4 Pre → PC，48 V OFF")},
      {wxT("Loopback 基准"),
       wxT("将 E4x4 Pre 的线路输出直接回接线路输入。\n"
           "运行 1 kHz FFT/THD，记录接口自身基波、THD 和 Noise Floor。\n"
           "后续 DUT 结果必须与这组基线比较，不能把声卡自身噪声算进 SA-440F5。"),
       wxT("OUT → IN 直接回环")},
      {wxT("1 kHz 增益"),
       wxT("E4x4 Pre 输出 → SA-440F5 差分输入，SA-440F5 输出 → E4x4 Pre Line In。\n"
           "从小信号开始，目标约 10 mVpp 差分输入；40 dB 增益时输出约 1 Vpp。\n"
           "禁止在 SA 输出端额外并 50 Ω 终端，否则会产生约 6 dB 衰减。"),
       wxT("E4x4 Pre → SA-440F5 → Line In")},
      {wxT("Sweep 幅频响应"),
       wxT("使用 Sweep 页面测 20 Hz–40 kHz 音频段响应。\n"
           "建议 48–96 个点，输入保持小信号，避免任何级过载。\n"
           "E4x4 Pre 只负责音频段；100 kHz–20 MHz 仍需信号源/示波器/VNA。"),
       wxT("20 Hz → 40 kHz 扫频")},
      {wxT("1 kHz THD"),
       wxT("切到 FFT / THD 页面，使用 Blackman-Harris 或 Hann 窗并增加平均次数。\n"
           "调节输入使 SA-440F5 输出约 1–2 Vpp，再读取 H2/H3 与 THD。\n"
           "结果必须高于 Loopback 基线足够多，才可归因于 DUT。"),
       wxT("1 kHz 基波 + H2/H3")},
      {wxT("低噪声测量"),
       wxT("将 SA-440F5 两个输入在 DUT 端短路，避免长线拾取。\n"
           "Line 输入先做粗测；需要更低噪声时可使用 E4x4 Pre 低噪声话放路径，48 V 必须关闭。\n"
           "最终按实际增益折算成输入端 nV/√Hz，并用 RSS 去除接口本底。"),
       wxT("输入短路 → FFT 平均 → RTI")},
      {wxT("结果复核与报告"),
       wxT("复核：1 kHz 增益、20 Hz–40 kHz Sweep、THD、Noise Floor。\n"
           "保存 FFT 与 Sweep CSV；记录 E4x4 Pre 设备名、采样率、Loopback 基线与 SA-440F5 设置。\n"
           "这一步完成后再进入 20 MHz 带宽、1 MHz CMRR 等高速仪器测试。"),
       wxT("保存 CSV + 测试条件 + 结论")}};
  const int count = sizeof(steps) / sizeof(steps[0]);
  if (m_saStep < 0) m_saStep = 0;
  if (m_saStep >= count) m_saStep = count - 1;

  label_sa_step_counter->SetLabel(wxString::Format(wxT("步骤 %d / %d"), m_saStep + 1, count));
  label_sa_step_title->SetLabel(steps[m_saStep].title);
  label_sa_step_body->SetLabel(steps[m_saStep].body);
  label_sa_step_body->Wrap(420);
  gauge_sa_progress->SetValue(m_saStep + 1);
  button_sa_prev->Enable(m_saStep > 0);
  button_sa_next->SetLabel(m_saStep == count - 1 ? wxT("完成") : wxT("下一步"));

  wxFileName exe(wxStandardPaths::Get().GetExecutablePath());
  const wxString imageName =
      wxString::Format(wxT("sa440f5_step_%02d.png"), m_saStep + 1);
  const wxString imagePath = exe.GetPathWithSep() + wxT("guide_assets") +
                             wxFileName::GetPathSeparator() + imageName;
  wxBitmap guide;
  if (wxFileExists(imagePath)) {
    wxImage image(imagePath);
    if (image.IsOk()) {
      image.Rescale(620, 360, wxIMAGE_QUALITY_HIGH);
      guide = wxBitmap(image);
    }
  }
  if (!guide.IsOk()) {
    guide = MakeGuidePlaceholder(steps[m_saStep].title, steps[m_saStep].guide, wxSize(620, 360));
  }
  bitmap_sa_guide->SetBitmap(guide);
  notebook_1_sa->Layout();
}

void MainFrame::AutoDetectE4x4(bool showMessage) {
  if (!m_RWAudio) return;
  unsigned int rec = 0;
  unsigned int play = 0;
  unsigned int rate = 96000;
  std::string name;
  const std::vector<std::string> hints = {"E4x4 Pre", "E4x4", "TOPPING"};

  if (m_RWAudio->AutoDetectDevice(hints, &rec, &play, &rate, &name)) {
    m_e4x4Name = wxString(name.c_str(), wxConvUTF8);
    const bool exactModel = m_e4x4Name.Lower().Find(wxT("e4x4")) != wxNOT_FOUND;
    m_e4x4Detected = exactModel;
    m_RecordDev = rec;
    m_PlayDev = play;
    m_SamplingFreq = rate;
    m_RWAudio->SetSndDevices(rec, play, rate);
    setoscbuf();
    m_RWAudio->ChangeBufLen((long int)m_OscBufferLength, (long int)m_SpeBufferLength);

    if (exactModel) {
      label_device_status->SetLabel(wxT("● 已识别 E4x4 Pre"));
      label_device_status->SetForegroundColour(wxColour(91, 214, 141));
      frame_1_statusbar->SetStatusText(
          wxString::Format(wxT("E4x4 Pre 已连接 · %u Hz · 可开始测试"), m_SamplingFreq));
    } else {
      label_device_status->SetLabel(wxT("● 已识别 TOPPING 音频设备（请确认 E4x4 型号）"));
      label_device_status->SetForegroundColour(wxColour(255, 191, 92));
      frame_1_statusbar->SetStatusText(
          wxString::Format(wxT("TOPPING 音频设备已连接 · %u Hz · 型号待确认"), m_SamplingFreq));
    }

    label_device_detail->SetLabel(
        wxString::Format(wxT("%s · %u Hz · 输入/输出自动绑定"), m_e4x4Name.c_str(), m_SamplingFreq));
    if (showMessage)
      wxMessageBox(
          wxString::Format(wxT("已识别：%s\n采样率：%u Hz\n%s"), m_e4x4Name.c_str(),
                           m_SamplingFreq,
                           exactModel ? wxT("型号匹配 E4x4。") : wxT("驱动名称未包含 E4x4，请人工确认型号。")),
          wxT("TOPPING 音频接口"), wxOK | wxICON_INFORMATION, this);
  } else {
    m_e4x4Detected = false;
    m_e4x4Name = wxEmptyString;
    label_device_status->SetLabel(wxT("○ 未自动识别 E4x4 Pre"));
    label_device_status->SetForegroundColour(wxColour(255, 191, 92));
    label_device_detail->SetLabel(
        wxT("仍可使用其他声卡；也可点击“音频接口设置”手动选择。"));
    if (showMessage)
      wxMessageBox(wxT("未发现名称包含 E4x4 / E4x4 Pre / TOPPING 的双向音频设备。"),
                   wxT("设备检测"), wxOK | wxICON_WARNING, this);
  }
}

void MainFrame::OnSAStart(wxCommandEvent& WXUNUSED(event)) {
  choice_fft->SetSelection(3);
  choice_fftlength->SetSelection(9);
  choice_fftavg->SetSelection(3);
  choice_fftrx->SetSelection(1);
  m_SpeBufferLength = 65536;
  m_SMASpeLeft->SetNumRecords(m_SpeBufferLength >> 1);
  m_SMASpeRight->SetNumRecords(m_SpeBufferLength >> 1);
  m_SMASpeLeft->SetNumAverage(10);
  m_SMASpeRight->SetNumAverage(10);
  setoscbuf();
  m_RWAudio->ChangeBufLen((long int)m_OscBufferLength, (long int)m_SpeBufferLength);
  text_ctrl1_frm->SetValue(wxT("48"));
  checkbox_gen_sync->SetValue(true);
  txt_freq_l->SetValue(wxT("1000"));
  txt_freq_r->SetValue(wxT("1000"));
  m_saStep = 0;
  AutoDetectE4x4(false);
  UpdateSA440F5Step();
}

void MainFrame::OnSAPrev(wxCommandEvent& WXUNUSED(event)) {
  if (m_saStep > 0) --m_saStep;
  UpdateSA440F5Step();
}

void MainFrame::OnSANext(wxCommandEvent& WXUNUSED(event)) {
  if (m_saStep < 6) ++m_saStep;
  UpdateSA440F5Step();
}

void MainFrame::OnSARepeat(wxCommandEvent& WXUNUSED(event)) { UpdateSA440F5Step(); }

void MainFrame::OnSAAudioSetup(wxCommandEvent& WXUNUSED(event)) {
  wxCommandEvent dummy;
  OnSelectSndCard(dummy);
}

void MainFrame::OnDeviceRefresh(wxCommandEvent& WXUNUSED(event)) { AutoDetectE4x4(true); }

void MainFrame::do_layout() {
  // begin wxGlade: MainFrame::do_layout
  wxBoxSizer* sizer_notebook = new wxBoxSizer(wxVERTICAL);
  wxBoxSizer* sizer_2 = new wxBoxSizer(wxVERTICAL);
  wxBoxSizer* sizer_3 = new wxBoxSizer(wxHORIZONTAL);
  wxBoxSizer* sizer_spe_9 = new wxBoxSizer(wxVERTICAL);
  wxBoxSizer* sizer_spe_10 = new wxBoxSizer(wxHORIZONTAL);
  wxBoxSizer* sizer_9 = new wxBoxSizer(wxVERTICAL);
  wxBoxSizer* sizer_10 = new wxBoxSizer(wxHORIZONTAL);
  wxBoxSizer* sizer_11 = new wxBoxSizer(wxVERTICAL);
  wxBoxSizer* sizer_11B = new wxBoxSizer(wxHORIZONTAL);
  wxStaticBoxSizer* sizer_12L = new wxStaticBoxSizer(sizer_osc_l_staticbox, wxVERTICAL);
  wxBoxSizer* sizer_16L = new wxBoxSizer(wxHORIZONTAL);
  wxBoxSizer* sizer_15L = new wxBoxSizer(wxHORIZONTAL);
  wxBoxSizer* sizer_14L = new wxBoxSizer(wxHORIZONTAL);
  wxStaticBoxSizer* sizer_12R = new wxStaticBoxSizer(sizer_osc_r_staticbox, wxVERTICAL);
  wxStaticBoxSizer* sizer_12H = new wxStaticBoxSizer(sizer_osc_h_staticbox, wxVERTICAL);
  wxBoxSizer* sizer_16R = new wxBoxSizer(wxHORIZONTAL);
  wxBoxSizer* sizer_15R = new wxBoxSizer(wxHORIZONTAL);
  wxBoxSizer* sizer_14R = new wxBoxSizer(wxHORIZONTAL);
  wxBoxSizer* sizer_13 = new wxBoxSizer(wxHORIZONTAL);
  wxStaticBoxSizer* sizer_GenEnL = new wxStaticBoxSizer(sizer_gen_l_staticbox, wxVERTICAL);
  wxStaticBoxSizer* sizer_GenEnR = new wxStaticBoxSizer(sizer_gen_r_staticbox, wxVERTICAL);
  wxBoxSizer* sizer_gen_sync = new wxBoxSizer(wxHORIZONTAL);
  wxBoxSizer* sizer_gen_sync2 = new wxBoxSizer(wxHORIZONTAL);

  wxBoxSizer* sizer_9_frm = new wxBoxSizer(wxVERTICAL);
  wxBoxSizer* sizer_10_frm = new wxBoxSizer(wxHORIZONTAL);
  wxBoxSizer* sizer_17_frm = new wxBoxSizer(wxVERTICAL);

  wxBoxSizer* sizer_txtfreql = new wxBoxSizer(wxVERTICAL);
  wxBoxSizer* sizer_txtfreqr = new wxBoxSizer(wxVERTICAL);

  wxFlexGridSizer* sizer_GenL = new wxFlexGridSizer(3, 2, 5, 5);
  wxFlexGridSizer* sizer_GenR = new wxFlexGridSizer(3, 2, 5, 5);

  wxBoxSizer* sizer_spe_ctrl = new wxBoxSizer(wxVERTICAL);
  wxBoxSizer* sizer_spe_metrics = new wxBoxSizer(wxHORIZONTAL);
  wxBoxSizer* sizer_spe_window = new wxBoxSizer(wxHORIZONTAL);
  wxBoxSizer* sizer_spe_samples = new wxBoxSizer(wxHORIZONTAL);
  wxBoxSizer* sizer_spe_span = new wxBoxSizer(wxHORIZONTAL);
  wxBoxSizer* sizer_spe_avg = new wxBoxSizer(wxHORIZONTAL);
  wxBoxSizer* sizer_spe_ref = new wxBoxSizer(wxHORIZONTAL);
  wxBoxSizer* sizer_spe_dbdiv = new wxBoxSizer(wxHORIZONTAL);
  wxStaticBoxSizer* sizer_spe_fft = new wxStaticBoxSizer(sizer_spe_fft_staticbox, wxVERTICAL);
  wxStaticBoxSizer* sizer_spe_disp = new wxStaticBoxSizer(sizer_spe_disp_staticbox, wxVERTICAL);
  wxStaticBoxSizer* sizer_spe_scale = new wxStaticBoxSizer(sizer_spe_scale_staticbox, wxVERTICAL);
  wxStaticBoxSizer* sizer_frm_prop = new wxStaticBoxSizer(sizer_frm_prop_staticbox, wxVERTICAL);

  // generator
  sizer_GenEnL->Add(checkbox_l_en, 0, wxALL | wxALIGN_CENTER_HORIZONTAL | wxALIGN_CENTER_VERTICAL,
                    5);
  sizer_GenL->Add(label_gen_wave_l, 0, wxALL | wxALIGN_LEFT | wxALIGN_CENTER_VERTICAL, 5);
  sizer_GenL->Add(choice_l_wav, 1, wxALL | wxEXPAND, 5);
  sizer_GenL->Add(label__gen_freq_l, 0, wxALL | wxALIGN_LEFT | wxALIGN_CENTER_VERTICAL, 5);
  sizer_txtfreql->Add(slide_l_fr, 0, wxEXPAND, 5);
  sizer_txtfreql->Add(txt_freq_l, wxALL | wxEXPAND, 5);
  sizer_GenL->Add(sizer_txtfreql, 1, wxALL | wxEXPAND, 5);
  sizer_GenL->Add(label_gen_ampl_l, 0, wxALL | wxALIGN_LEFT | wxALIGN_CENTER_VERTICAL, 5);
  sizer_GenL->Add(slide_l_am, 1, wxEXPAND, 5);
  sizer_GenEnL->Add(sizer_GenL, 0, wxALL | wxEXPAND, 5);
  sizer_3->Add(sizer_GenEnL, 0, wxALL | wxEXPAND, 5);

  sizer_GenEnR->Add(checkbox_r_en, 0, wxALL | wxALIGN_CENTER_HORIZONTAL | wxALIGN_CENTER_VERTICAL,
                    5);
  sizer_GenR->Add(label_gen_wave_r, 0, wxALL | wxALIGN_LEFT | wxALIGN_CENTER_VERTICAL, 5);
  sizer_GenR->Add(choice_r_wav, 1, wxALL | wxEXPAND, 5);
  sizer_GenR->Add(label_gen_freq_r, 0, wxALL | wxALIGN_LEFT | wxALIGN_CENTER_VERTICAL, 5);
  sizer_txtfreqr->Add(slide_r_fr, 0, wxEXPAND, 5);
  sizer_txtfreqr->Add(txt_freq_r, wxALL | wxEXPAND, 5);
  sizer_GenR->Add(sizer_txtfreqr, 1, wxALL | wxEXPAND, 5);
  sizer_GenR->Add(label_gen_ampl_r, 0, wxALL | wxALIGN_LEFT | wxALIGN_CENTER_VERTICAL, 5);
  sizer_GenR->Add(slide_r_am, 1, wxEXPAND, 5);
  sizer_GenEnR->Add(sizer_GenR, 0, wxALL | wxEXPAND, 5);
  sizer_3->Add(sizer_GenEnR, 0, wxALL | wxEXPAND, 5);

  sizer_2->Add(sizer_3, 0, wxALIGN_CENTER_HORIZONTAL, 0);
  sizer_gen_sync->Add(checkbox_gen_sync, 0,
                      wxALL | wxALIGN_CENTER_HORIZONTAL | wxALIGN_CENTER_VERTICAL, 5);
  sizer_gen_sync2->Add(label_gen_sync, 0,
                       wxALL | wxALIGN_CENTER_HORIZONTAL | wxALIGN_CENTER_VERTICAL, 5);
  sizer_gen_sync2->Add(text_gen_sync, 0,
                       wxALL | wxALIGN_CENTER_HORIZONTAL | wxALIGN_CENTER_VERTICAL, 5);
  sizer_2->Add(sizer_gen_sync, 0, wxALIGN_CENTER_HORIZONTAL, 0);
  sizer_2->Add(sizer_gen_sync2, 0, wxALIGN_CENTER_HORIZONTAL, 0);
  sizer_2->Add(button_gen_start, 0, wxALL | wxALIGN_CENTER_HORIZONTAL | wxALIGN_CENTER_VERTICAL, 5);
  notebook_1_gen->SetAutoLayout(true);
  notebook_1_gen->SetSizer(sizer_2);
  sizer_2->Fit(notebook_1_gen);
  sizer_2->SetSizeHints(notebook_1_gen);

  // oscilloscope
  sizer_10->Add(window_osc, 1, wxEXPAND, 0);  // CtrlOScope

  // sizer_14: wxHorizontal
  sizer_14L->Add(label_osc_div_l, 0, wxLEFT | wxALIGN_CENTER_HORIZONTAL | wxALIGN_CENTER_VERTICAL,
                 5);                              // Res[V/Div]
  sizer_14L->Add(5, 5, 1, 0, 0);                  // spacer
  sizer_14L->Add(choice_osc_l_res, 0, wxALL, 5);  // 2, 4, 8......32768
  // sizer_12L: StaticBox Left Channel
  sizer_12L->Add(sizer_14L, 1, wxEXPAND, 0);
  sizer_15L->Add(label_osc_off_l, 0,
                 wxLEFT | wxRIGHT | wxALIGN_CENTER_HORIZONTAL | wxALIGN_CENTER_VERTICAL,
                 5);              // Offset [V/div]
  sizer_15L->Add(5, 5, 1, 0, 0);  // spacer
  sizer_15L->Add(choice_osc_l_off, 0, wxLEFT | wxRIGHT | wxALIGN_CENTER_VERTICAL,
                 5);  // 100, 80, ... -100
  sizer_12L->Add(sizer_15L, 1, wxEXPAND, 0);

  sizer_11B->Add(button_autocalibrate, 0, wxLEFT | wxALIGN_CENTER_VERTICAL, 5);
  sizer_11B->Add(5, 5, 1, 0, 0);  // spacer
  sizer_11B->Add(button_sinc, 0, wxRIGHT | wxALIGN_CENTER_VERTICAL, 5);
  sizer_11->Add(sizer_11B, 0, wxALL | wxEXPAND, 5);

  sizer_11->Add(sizer_12L, 0, wxALL | wxEXPAND, 5);

  sizer_14R->Add(label_osc_div_r, 0, wxLEFT | wxALIGN_CENTER_HORIZONTAL | wxALIGN_CENTER_VERTICAL,
                 5);                              // Res[V/div]
  sizer_14R->Add(5, 5, 1, 0, 0);                  // spacer
  sizer_14R->Add(choice_osc_r_res, 0, wxALL, 5);  // 2, 4, ... 32768
  // sizer_12R: StaticBox Right Channel
  sizer_12R->Add(sizer_14R, 1, wxEXPAND, 0);
  sizer_15R->Add(label_osc_off_r, 0,
                 wxLEFT | wxRIGHT | wxALIGN_CENTER_HORIZONTAL | wxALIGN_CENTER_VERTICAL,
                 5);              // Offset [V/div]
  sizer_15R->Add(5, 5, 1, 0, 0);  // spacer
  sizer_15R->Add(choice_osc_r_off, 0, wxLEFT | wxRIGHT | wxALIGN_CENTER_VERTICAL,
                 5);  // 100, 80, ... -100
  sizer_12R->Add(sizer_15R, 1, wxEXPAND, 0);
  sizer_11->Add(sizer_12R, 0, wxALL | wxEXPAND, 5);

  // sizer_13: wxHORIZONTAL
  sizer_13->Add(label_osc_time, 0, wxALL | wxALIGN_CENTER_VERTICAL, 5);  // X Scale time
  sizer_13->Add(5, 5, 1, 0, 0);                                          // spacer
  sizer_13->Add(choice_osc_swp, 0, wxALL | wxALIGN_CENTER_VERTICAL, 5);  // 20, 50....50000
  sizer_12H->Add(sizer_13, 1, wxEXPAND, 0);

  sizer_16L->Add(label_osc_trig, 0, wxALL | wxALIGN_CENTER_VERTICAL, 5);  // Trigger
  sizer_16L->Add(5, 5, 1, 0, 0);                                          // spacer
  sizer_16L->Add(choice_osc_trig_source, 0, wxALL | wxALIGN_CENTER_VERTICAL,
                 5);  // Off, Channel
  sizer_16L->Add(choice_osc_trig_edge, 0, wxALL | wxALIGN_CENTER_VERTICAL,
                 5);  // Rising, falling
  sizer_12H->Add(sizer_16L, 1, wxEXPAND, 0);

  sizer_16R->Add(label_osc_level, 0, wxALL | wxALIGN_CENTER_VERTICAL, 5);  // Trigger Edge
  sizer_16R->Add(slide_osc_level, 1, wxEXPAND, 5);                         // level
  sizer_12H->Add(sizer_16R, 1, wxEXPAND, 0);

  sizer_11->Add(sizer_12H, 0, wxALL | wxEXPAND, 5);
  sizer_10->Add(sizer_11, 0, 0, 0);
  sizer_9->Add(sizer_10, 1, wxEXPAND, 0);
  sizer_9->Add(button_osc_start, 0, wxALL | wxALIGN_CENTER_HORIZONTAL | wxALIGN_CENTER_VERTICAL, 5);
  notebook_1_osc->SetAutoLayout(true);
  notebook_1_osc->SetSizer(sizer_9);
  sizer_9->Fit(notebook_1_osc);
  sizer_9->SetSizeHints(notebook_1_osc);

  // spectrum analyzer
  sizer_spe_10->Add(window_1_spe, 1, wxEXPAND, 0);
  wxSize window_1_spe_size = window_1_spe->GetSize();
  sizer_spe_10->SetMinSize(4 * window_1_spe_size.GetHeight(), window_1_spe_size.GetHeight());
  sizer_spe_window->Add(label_5, 0, wxLEFT | wxALIGN_CENTER_HORIZONTAL | wxALIGN_CENTER_VERTICAL,
                        5);
  sizer_spe_window->Add(5, 5, 1, 0, 0);
  sizer_spe_window->Add(choice_fft, 0, wxALL, 5);
  sizer_spe_fft->Add(sizer_spe_window, 1, wxEXPAND, 0);

  sizer_spe_samples->Add(label_9, 0, wxLEFT | wxALIGN_CENTER_HORIZONTAL | wxALIGN_CENTER_VERTICAL,
                         5);
  sizer_spe_samples->Add(5, 5, 1, 0, 0);
  sizer_spe_samples->Add(choice_fftlength, 0, wxALL, 5);
  sizer_spe_fft->Add(sizer_spe_samples, 1, wxEXPAND, 0);
  sizer_spe_ctrl->Add(sizer_spe_fft, 0, wxALL | wxEXPAND, 5);

  sizer_spe_span->Add(label_rx, 0, wxALL | wxALIGN_CENTER_HORIZONTAL | wxALIGN_CENTER_VERTICAL, 5);
  sizer_spe_span->Add(5, 5, 1, 0, 0);
  sizer_spe_span->Add(choice_fftrx, 0, wxALL, 5);
  sizer_spe_disp->Add(sizer_spe_span, 1, wxEXPAND, 0);

  sizer_spe_avg->Add(label_avg, 0, wxALL | wxALIGN_CENTER_HORIZONTAL | wxALIGN_CENTER_VERTICAL, 5);
  sizer_spe_avg->Add(5, 5, 1, 0, 0);
  sizer_spe_avg->Add(choice_fftavg, 0, wxALL, 5);
  sizer_spe_disp->Add(sizer_spe_avg, 1, wxEXPAND, 0);
  sizer_spe_ctrl->Add(sizer_spe_disp, 0, wxALL | wxEXPAND, 5);

  sizer_spe_ref->Add(label_spe_ref, 0, wxALL | wxALIGN_CENTER_HORIZONTAL | wxALIGN_CENTER_VERTICAL,
                     5);
  sizer_spe_ref->Add(5, 5, 1, 0, 0);
  sizer_spe_ref->Add(choice_spe_ref, 0, wxALL, 5);
  sizer_spe_scale->Add(sizer_spe_ref, 1, wxEXPAND, 0);

  sizer_spe_dbdiv->Add(label_spe_dbdiv, 0,
                       wxALL | wxALIGN_CENTER_HORIZONTAL | wxALIGN_CENTER_VERTICAL, 5);
  sizer_spe_dbdiv->Add(5, 5, 1, 0, 0);
  sizer_spe_dbdiv->Add(choice_spe_dbdiv, 0, wxALL, 5);
  sizer_spe_scale->Add(sizer_spe_dbdiv, 1, wxEXPAND, 0);
  sizer_spe_ctrl->Add(sizer_spe_scale, 0, wxALL | wxEXPAND, 5);

  sizer_spe_10->Add(sizer_spe_ctrl, 0, wxEXPAND, 0);
  sizer_spe_9->Add(sizer_spe_10, 1, wxEXPAND, 0);
  wxFont metricFont = label_thd_value->GetFont();
  metricFont.SetPointSize(metricFont.GetPointSize() + 2);
  metricFont.SetWeight(wxFONTWEIGHT_BOLD);
  label_fft_freq_value->SetFont(metricFont);
  label_fft_mag_value->SetFont(metricFont);
  label_thd_value->SetFont(metricFont);
  sizer_spe_metrics->Add(label_fft_freq_value, 1, wxALL | wxALIGN_CENTER_VERTICAL, 8);
  sizer_spe_metrics->Add(label_fft_mag_value, 1, wxALL | wxALIGN_CENTER_VERTICAL, 8);
  sizer_spe_metrics->Add(label_thd_value, 1, wxALL | wxALIGN_CENTER_VERTICAL, 8);
  sizer_spe_9->Add(sizer_spe_metrics, 0, wxLEFT | wxRIGHT | wxEXPAND, 8);
  sizer_spe_9->Add(button_spe_start, 0, wxALL | wxALIGN_CENTER_HORIZONTAL | wxALIGN_CENTER_VERTICAL,
                   8);
  notebook_1_spe->SetAutoLayout(true);
  notebook_1_spe->SetSizer(sizer_spe_9);
  sizer_spe_9->Fit(notebook_1_spe);
  sizer_spe_9->SetSizeHints(notebook_1_spe);

  // frequency response
  sizer_17_frm->Add(label_1_frm, 0, wxALL | wxALIGN_CENTER_HORIZONTAL | wxALIGN_CENTER_VERTICAL, 5);
  sizer_17_frm->Add(text_ctrl1_frm, 0, wxALL | wxALIGN_CENTER_HORIZONTAL | wxALIGN_CENTER_VERTICAL,
                    5);
  sizer_frm_prop->Add(sizer_17_frm, 0, wxALL | wxEXPAND, 5);
  sizer_10_frm->Add(window_1_frm, 1, wxEXPAND, 0);
  sizer_10_frm->Add(sizer_frm_prop, 0, wxALL | wxEXPAND, 5);
  sizer_9_frm->Add(sizer_10_frm, 1, wxEXPAND, 0);
  sizer_9_frm->Add(button_frm_start, 0, wxALL | wxALIGN_CENTER_HORIZONTAL | wxALIGN_CENTER_VERTICAL,
                   5);
  notebook_1_frm->SetAutoLayout(true);
  notebook_1_frm->SetSizer(sizer_9_frm);
  sizer_9_frm->Fit(notebook_1_frm);
  sizer_9_frm->SetSizeHints(notebook_1_frm);

  // main notebook - instrument workflow first; generator/scope remain internal helpers.
  notebook_1->AddPage(notebook_1_home, wxT("仪器总览"));
  notebook_1->AddPage(notebook_1_spe, wxT("FFT / THD"));
  notebook_1->AddPage(notebook_1_frm, wxT("Sweep 扫频"));
  notebook_1->AddPage(notebook_1_sa, wxT("SA-440F5 一键测试"));
  notebook_1_gen->Hide();
  notebook_1_osc->Hide();
  notebook_1->SetSelection(0);
  sizer_notebook->Add(notebook_1, 1, wxEXPAND, 0);
  SetAutoLayout(true);
  SetSizer(sizer_notebook);
  SetMinSize(wxSize(1180, 760));
  SetSize(wxSize(1280, 820));
  Layout();
  // end wxGlade
}

void MainFrame::setoscbuf() {
  m_OscBufferLength = (unsigned long)(2 + sweep_div * 10E-6 * m_SamplingFreq);
}

void MainFrame::set_custom_props() {
#ifdef __WXMSW__
  SetIcon(wxICON(AudMeSIcon));
#endif

#ifdef __LINUX__
#include "audmes.xpm"
  SetIcon(wxICON(audmes));
#endif

  m_PlayDev = 0;
  m_RecordDev = 0;
  m_SamplingFreq = 44100;
  m_e4x4Detected = false;
  m_e4x4Name = wxEmptyString;

  sweep_div = wxAtoi(choice_osc_swp->GetString(choice_osc_swp->GetSelection()));
  setoscbuf();

  /* oscilloscope */
  window_osc->SetXRange(0, sweep_div * 10E-6, 0);
  window_osc->SetYRange(-1, 1, 0);
  window_osc->SetNumOfVerticals(10);
  range_div = 1;
  shft_val = 0;
  range_div2 = 1;
  shft_val2 = 0;
  trigger_channel = 0;
  trigger_edge = 1.0;
  trigger_level = 0.0;
  trigger_pre = 0;

  /* analyzer */
  window_1_spe->SetXRange(20, 20000, 1);
  window_1_spe->SetYRange(-100, 0, 0);

  /* freq response */
  window_1_frm->SetXRange(20, 20000, 1);
  window_1_frm->SetYRange(-80, 0, 0);

  frm_running = 0;
  frm_measure = 0;
  frm_istep = 0;

  m_configfilename = wxT("");

  m_timer = new wxTimer(this, ID_TIMERID);
  m_timer->Start(100);

  m_SpeBufferLength = wxAtoi(choice_fftlength->GetString(choice_fftlength->GetSelection()));

  m_RWAudio = new RWAudio();
  m_SMASpeLeft = new SMA_2D(m_SpeBufferLength >> 1, 1);
  m_SMASpeRight = new SMA_2D(m_SpeBufferLength >> 1, 1);

  int ret = 0;

  ret = m_RWAudio->InitSnd((long int)(m_OscBufferLength), m_SpeBufferLength, m_rtinfo,
                           m_SamplingFreq);

  if (ret) {
    wxMessageBox(_T("音频接口初始化失败。\n\n请检查：工具 → 音频接口设置"),
                 _T("音频接口"), wxICON_INFORMATION | wxOK);
  }

  ApplyInstrumentTheme(this);
  if (!ret) AutoDetectE4x4(false);
}

void MainFrame::OnAboutClick(wxCommandEvent& WXUNUSED(event)) {
  wxString s;
  s << wxT("AudMeS 测试分析仪 - ") << AUDMES_VERSION_STRING
    << wxT("\n\n基于 AudMeS GPLv2 开源项目继续开发。")
    << wxT("\n原作者：Vaclav Peroutka")
    << wxT("\n上游：https://sourceforge.net/projects/audmes/")
    << wxT("\n\n当前重点：FFT / THD / Sweep / E4x4 Pre / SA-440F5")
    << wxT("\n\n") << m_rtinfo;

  wxMessageBox(s, _T("关于 AudMeS"), wxICON_INFORMATION | wxOK);
}

void MainFrame::OnExitClick(wxCommandEvent& WXUNUSED(event)) { Close(); }

void MainFrame::OnClose(wxCloseEvent& WXUNUSED(event)) {
  m_timer->Stop();
  Destroy();
}

void MainFrame::OnOpenClick(wxCommandEvent& WXUNUSED(event)) {
  wxMessageBox(wxT("Not yet implemented"), _T("About application"), wxICON_INFORMATION | wxOK);
}

void MainFrame::OnSaveClick(wxCommandEvent& WXUNUSED(event)) {
  wxMessageBox(wxT("Not yet implemented"), _T("About application"), wxICON_INFORMATION | wxOK);
}

void MainFrame::OnSaveAsClick(wxCommandEvent& WXUNUSED(event)) {
  wxMessageBox(wxT("Not yet implemented"), _T("About application"), wxICON_INFORMATION | wxOK);
}

void MainFrame::OnSaveFRM(wxCommandEvent& WXUNUSED(event)) {
  wxFileDialog saveFileDialog(this, _("Save frequency response file"), "", "",
                              "CSV files (*.csv)|*.csv", wxFD_SAVE | wxFD_OVERWRITE_PROMPT);
  if (saveFileDialog.ShowModal() == wxID_CANCEL) return;

  std::ofstream frm;
  frm.open(saveFileDialog.GetPath().mb_str(), std::ios::trunc);
  if (!frm.is_open()) {
    wxLogError("Cannot save current contents in file '%s'.", saveFileDialog.GetPath());
    return;
  }
  frm << "Hz"
      << ","
      << "GainL"
      << ","
      << "GainR" << std::endl;
  for (unsigned int i = 0; i < frm_freqs.GetCount(); i++) {
    frm << frm_freqs[i] << "," << frm_lgains[i] << "," << frm_rgains[i] << std::endl;
  }
  frm.close();
}

void MainFrame::OnSaveSPE(wxCommandEvent& WXUNUSED(event)) {
  wxFileDialog saveFileDialog(this, _("Save frequency spectrum file"), "", "",
                              "CSV files (*.csv)|*.csv", wxFD_SAVE | wxFD_OVERWRITE_PROMPT);
  if (saveFileDialog.ShowModal() == wxID_CANCEL) return;

  std::ofstream spe;
  spe.open(saveFileDialog.GetPath().mb_str(), std::ios::trunc);
  if (!spe.is_open()) {
    wxLogError("Cannot save current contents in file '%s'.", saveFileDialog.GetPath());
    return;
  }
  spe << "Hz"
      << ","
      << "MagL"
      << ","
      << "MagR" << std::endl;
  for (unsigned int i = 0; i < spe_freqs.GetCount(); i++) {
    spe << spe_freqs[i] << "," << spe_lmagns[i] << "," << spe_rmagns[i] << std::endl;
  }
  spe.close();
}

void MainFrame::OnSaveOSC(wxCommandEvent& WXUNUSED(event)) {
  wxFileDialog saveFileDialog(this, _("Save oscillogram file"), "", "", "CSV files (*.csv)|*.csv",
                              wxFD_SAVE | wxFD_OVERWRITE_PROMPT);
  if (saveFileDialog.ShowModal() == wxID_CANCEL) return;

  std::ofstream osc;
  osc.open(saveFileDialog.GetPath().mb_str(), std::ios::trunc);
  if (!osc.is_open()) {
    wxLogError("Cannot save current contents in file '%s'.", saveFileDialog.GetPath());
    return;
  }
  osc << "time"
      << ","
      << "MagL"
      << ","
      << "MagR" << std::endl;
  for (unsigned int i = 0; i < osc_times.GetCount(); i++) {
    osc << osc_times[i] << "," << osc_lmagns[i] << "," << osc_rmagns[i] << std::endl;
  }
  osc.close();
}

void MainFrame::OnLoadFRM(wxCommandEvent& WXUNUSED(event)) {
  if (0 /* ...current content has not been saved... */) {
    if (wxMessageBox(_("Current content has not been saved! Proceed?"), _("Please confirm"),
                     wxICON_QUESTION | wxYES_NO, this) == wxNO)
      return;
  }

  wxFileDialog openFileDialog(this, _("Open frequency response file"), "", "",
                              "CSV files (*.csv)|*.csv", wxFD_OPEN | wxFD_FILE_MUST_EXIST);
  if (openFileDialog.ShowModal() == wxID_CANCEL) return;

  io::CSVReader<3> in(openFileDialog.GetPath());
  in.read_header(io::ignore_extra_column, "Hz", "GainL", "GainR");

  frm_freqs.Clear();
  frm_lgains.Clear();
  frm_rgains.Clear();
  double hz;
  double gainl, gainr;
  while (in.read_row(hz, gainl, gainr)) {
    frm_freqs.Add(hz);
    frm_lgains.Add(gainl);
    frm_rgains.Add(gainr);
  }
  DrawFreqResponse();
  Refresh();
}

void MainFrame::OnAutoCalClick(wxCommandEvent& WXUNUSED(event)) {
  if (button_osc_start->GetValue()) {
    float minValueL = 1;
    float maxValueL = -1;
    float minValueR = 1;
    float maxValueR = -1;

    for (unsigned long int i = 0; i < m_OscBufferLength; i++) {
      if (minValueL > g_OscBuffer_Left[i]) minValueL = g_OscBuffer_Left[i];
      if (maxValueL < g_OscBuffer_Left[i]) maxValueL = g_OscBuffer_Left[i];
      if (minValueR > g_OscBuffer_Right[i]) minValueR = g_OscBuffer_Right[i];
      if (maxValueR < g_OscBuffer_Right[i]) maxValueR = g_OscBuffer_Right[i];
    }

    auto diff = 1 / (maxValueL - minValueL);
    auto lgdiff = log(diff) / log(2);
    if (lgdiff > 13) lgdiff = 13;
    choice_osc_l_res->SetSelection((int)lgdiff);

    diff = 1 / (maxValueR - minValueR);
    lgdiff = log(diff) / log(2);
    if (lgdiff > 13) lgdiff = 13;
    choice_osc_r_res->SetSelection((int)lgdiff);
    wxCommandEvent dummy;
    OnXScaleChanged(dummy);
  } else {
    wxMessageBox(wxT("Please start recording"), _T("Could not auto calibrate"),
                 wxICON_INFORMATION | wxOK);
  }
}

void MainFrame::OnSincClick(wxCommandEvent& WXUNUSED(event)) {
  if (button_sinc->GetValue()) {
    window_osc->SetInterp(CtrlOScope::Interpolation::SINC);
  } else {
    window_osc->SetInterp(CtrlOScope::Interpolation::LINE);
  }
  Refresh();
}

static const int frm_low = 20;

void MainFrame::CalcFreqResponse() {
  /* periodically called by OnTimer
   * delays for measuring work by waiting for the next call
   */
  if (frm_istep <= (int)frm_ipoints) {
    float freq = frm_low * pow(10.0, 3.0 * frm_istep / frm_ipoints);

    if (0 == frm_measure) {
      // play new frequency e.g. from 20Hz to 20kHz
      m_RWAudio->PlaySetGenerator(freq, freq, RWAudio::SINE, RWAudio::SINE,
                                  pow(10, slide_l_am->GetValue() / 20.0),
                                  pow(10, slide_r_am->GetValue() / 20.0));
      wxString bla;
      bla.Printf(wxT("Frequency : %.1f "), freq);
      window_1_frm->ShowUserText(bla, 100, 20);
    }
    if (1 == frm_measure) g_SpeBufferChanged.store(false);  // now get audio data

    if (g_SpeBufferChanged.load() && frm_measure > 1) {
      // new audio data has arrived
      double l_rms = 0;
      double r_rms = 0;
      // compute RMS value in the grabbed wave and store it as a result
      for (unsigned long int ii = 0; ii < m_SpeBufferLength; ii++) {
        l_rms += g_SpeBuffer_Left[ii] * g_SpeBuffer_Left[ii];
        r_rms += g_SpeBuffer_Right[ii] * g_SpeBuffer_Right[ii];
      }
      frm_freqs.Add(freq);
      frm_lgains.Add(sqrt(l_rms / m_SpeBufferLength));
      frm_rgains.Add(sqrt(r_rms / m_SpeBufferLength));
      frm_measure = -1;  // zero after increment
      frm_istep++;
    }
    frm_measure++;
  } else {
    frm_running = false;
    window_1_frm->ShowUserText(wxString(""), 0, 0);
    button_frm_start->SetValue(false);
    button_frm_start->SetLabel(_T("开始扫频"));
    m_RWAudio->StopSnd();
    SendGenSettings();  // stop generator
  }
}

void MainFrame::DrawFreqResponse(void) {
  wxArrayDouble left, right;
  double tmpval;
  left.Clear();
  right.Clear();
  for (unsigned int i = 0; i < frm_freqs.size(); i++) {
    tmpval = frm_lgains[i];
    left.Add(20.0 * log10(tmpval));
    tmpval = frm_rgains[i];
    right.Add(20.0 * log10(tmpval));
  }
  window_1_frm->SetTrack1(left);
  window_1_frm->SetTrack2(right);
  window_1_frm->SetTrackX(frm_freqs);
}

void MainFrame::DrawOscilloscope(void) {
  osc_lmagns.Clear();
  osc_rmagns.Clear();
  osc_times.Clear();

  for (unsigned long i = 0; i < m_OscBufferLength; i++) {
    osc_lmagns.Add(g_OscBuffer_Left[i] / range_div - shft_val);
    osc_rmagns.Add(g_OscBuffer_Right[i] / range_div2 - shft_val2);
    osc_times.Add((double)i / m_SamplingFreq);
  }

  window_osc->SetTrack1(osc_lmagns);
  window_osc->SetTrack2(osc_rmagns);
  window_osc->SetTrackX(osc_times);
}

double MainFrame::calc_dc(const float* data, int size) {
  double dc = 0.0;
  for (int i = 0; i < size; i++) {
    dc += data[i];
  }
  return dc / size;
}

void MainFrame::DrawSpectrum(void) {
  double *realin, *realout, *imagout, *windowf;
  int nsampl = m_SpeBufferLength;
  realin = (double*)malloc(nsampl * sizeof(double));
  realout = (double*)malloc(nsampl * sizeof(double));
  imagout = (double*)malloc(nsampl * sizeof(double));
  windowf = (double*)malloc(nsampl * sizeof(double));
  spe_freqs.Clear();
  spe_lmagns.Clear();
  spe_rmagns.Clear();

  // calculate window
  const double multiplier = 2 * M_PI / nsampl;
  switch (choice_fft->GetSelection()) {
    case 1:  // Hanning
      for (int i = 0; i < nsampl; i++) {
        windowf[i] = 2 * (0.5 + -0.5 * cos(i * multiplier)) / (double)nsampl;
      }
      break;
    case 2:  // Blackman
      for (int i = 0; i < nsampl; i++) {
        windowf[i] = 2.4 * (0.42 - 0.5 * cos(multiplier * i) + 0.08 * cos(2 * multiplier * i)) /
                     (double)nsampl;
      }
      break;
    case 3:  // Blackman Harris minimum 4 term
      for (int i = 0; i < nsampl; i++) {
        windowf[i] = 2.63 *
                     (0.35875 + -0.48829 * cos(i * multiplier) + 0.14128 * cos(i * multiplier * 2) +
                      -0.01168 * cos(i * multiplier * 3)) /
                     (double)nsampl;
      }
      break;
    default:  // Rectangle
      for (int i = 0; i < nsampl; i++) {
        windowf[i] = 1.0 / (double)nsampl;
      }
      break;
  }

  double dval = 0.0;
  double dmax = 0.0;
  double dval_db = 0.0;

  // left channel
  double offsetL = calc_dc(g_SpeBuffer_Left, nsampl);
  for (int i = 0; i < nsampl; i++) {
    // copy and apply window
    realin[i] = (g_SpeBuffer_Left[i] - offsetL) * windowf[i];
  }

  if (fft_double(nsampl, 0, realin, NULL, realout, imagout)) {
    // use only up to nsampl/2 and skip DC
    for (int i = 1; i < nsampl / 2; i++) {
      // multiply amplitude by 2 to compensate
      dval = 2 * sqrt(realout[i] * realout[i] + imagout[i] * imagout[i]);
      m_SMASpeLeft->AddVal(i, dval);
      dval_db = 20.0 * log10(m_SMASpeLeft->GetSMA(i));
      spe_lmagns.Add(dval_db);
    }
  } else {
    /* wrong computation */
    for (int i = 0; i < nsampl / 2; i++) {
      spe_lmagns.Add(-150);
    }
  }

  /* find frequency index with highest amplitude */
  int fmax = 0;
  for (int i = 0; i < nsampl / 2; i++) {
    if (m_SMASpeLeft->GetSMA(i) > dmax) {
      dmax = m_SMASpeLeft->GetSMA(i);
      fmax = i;
    }
  }

  /* use that frequency as base and calculate distortion
   * but only if the magnitude is above -90 db
   */
  double freq = 0.0;
  double thd = 0.0;
  double thdval[10] = {1.0E-6};
  if (fmax > 0 && dmax > 0.00003) {
    freq = (double)fmax * m_SamplingFreq / nsampl;
    for (int i = 0; i < 10; i++) {
      int j = fmax * (i + 1);
      if (j < nsampl / 2)
        thdval[i] = m_SMASpeLeft->GetSMA(j);
      else
        thdval[i] = 0.0;
    }
    double harmonicPower = 0.0;
    for (int i = 1; i < 10; ++i) harmonicPower += thdval[i] * thdval[i];
    if (thdval[0] > 0.0) thd = 100.0 * sqrt(harmonicPower) / thdval[0];
  }

  /* display base frequency, magnitude and distortion */
  const double magnitudeDb = thdval[0] > 0.0 ? 20.0 * log10(thdval[0]) : -150.0;
  label_fft_freq_value->SetLabel(wxString::Format(wxT("基波  %.2f Hz"), freq));
  label_fft_mag_value->SetLabel(wxString::Format(wxT("幅度  %.2f dBFS"), magnitudeDb));
  label_thd_value->SetLabel(wxString::Format(wxT("THD  %.6f %%"), thd));
  wxString freqency;
  freqency.Printf(wxT("基波 %.2f Hz · 幅度 %.2f dBFS · THD %.6f %% · 平均 %d/%d"), freq,
                  magnitudeDb, thd, m_SMASpeLeft->GetNumSummed(1),
                  m_SMASpeLeft->GetNumAverage());
  frame_1_statusbar->SetStatusText(freqency);

  // right channel
  double offsetR = calc_dc(g_SpeBuffer_Right, nsampl);
  for (int i = 0; i < nsampl; i++) {
    // copy and apply window
    realin[i] = (g_SpeBuffer_Right[i] - offsetR) * windowf[i];
  }

  if (fft_double(nsampl, 0, realin, NULL, realout, imagout)) {
    // use only up to nsampl/2 and skip DC
    for (int i = 1; i < nsampl / 2; i++) {
      dval = 2 * sqrt(realout[i] * realout[i] + imagout[i] * imagout[i]);
      m_SMASpeRight->AddVal(i, dval);
      dval_db = (20.0 * log10(m_SMASpeRight->GetSMA(i)));
      spe_rmagns.Add(dval_db);
    }
  } else {
    /* wrong computation */
    for (int i = 0; i < nsampl / 2; i++) {
      spe_rmagns.Add(-150);
    }
  }

  double fbase = (double)m_SamplingFreq / nsampl;
  // frequencies without DC
  for (int i = 1; i < nsampl / 2; i++) {
    spe_freqs.Add(fbase * i);
  }
  window_1_spe->SetTrack1(spe_lmagns);
  window_1_spe->SetTrack2(spe_rmagns);
  window_1_spe->SetTrackX(spe_freqs);
  switch (choice_fftrx->GetSelection()) {
    case 1:
      window_1_spe->SetXRange(20, 20000, 1);
      break;
    case 2:
      window_1_spe->SetXRange(10, 100000, 1);
      break;
    default:
      window_1_spe->SetXRange(2, 2000, 1);
      break;
  }
  free(realin);
  free(realout);
  free(imagout);
  free(windowf);
}

void MainFrame::OnTimer(wxTimerEvent& WXUNUSED(event)) {
  bool refresh = false;
  if (g_OscBufferChanged.load() && button_osc_start->GetValue()) {
    DrawOscilloscope();
    g_OscBufferChanged.store(false);
    refresh = true;
  }
  if (frm_running) {
    CalcFreqResponse();
    DrawFreqResponse();
    refresh = true;
  }
  if (g_SpeBufferChanged.load() && button_spe_start->GetValue()) {
    DrawSpectrum();
    refresh = true;
    g_SpeBufferChanged.store(false);
  }
  if (refresh) {
    Refresh();
    Update();
  }
}

void MainFrame::OnXScaleChanged(wxCommandEvent& WXUNUSED(event)) {
  sweep_div = wxAtoi(choice_osc_swp->GetString(choice_osc_swp->GetSelection()));
  setoscbuf();
  window_osc->SetXRange(0, sweep_div * 10E-6, 0);

  m_SpeBufferLength = wxAtoi(choice_fftlength->GetString(choice_fftlength->GetSelection()));

  m_RWAudio->ChangeBufLen((unsigned long)(m_OscBufferLength), m_SpeBufferLength);
  m_SMASpeLeft->SetNumRecords(m_SpeBufferLength >> 1);
  m_SMASpeRight->SetNumRecords(m_SpeBufferLength >> 1);

  const double range[] = {1, 2, 5, 10, 20, 50, 100, 200, 500, 1000, 2000, 5000, 10000, 20000};
  range_div = 1 / range[choice_osc_l_res->GetSelection()];
  shft_val = 20.0 * (choice_osc_l_off->GetSelection() - 5) / 100.0;
  range_div2 = 1 / range[choice_osc_r_res->GetSelection()];
  shft_val2 = 20.0 * (choice_osc_r_off->GetSelection() - 5) / 100.0;
  TriggerSettings();

  g_SpeBufferChanged.store(false);
  g_OscBufferChanged.store(false);
}

void MainFrame::OnFFTAvgChanged(wxCommandEvent& WXUNUSED(event)) {
  int numAverage = wxAtoi(choice_fftavg->GetString(choice_fftavg->GetSelection()));
  m_SMASpeLeft->SetNumAverage(numAverage);
  m_SMASpeRight->SetNumAverage(numAverage);
}

void MainFrame::OnFFTScaleChanged(wxCommandEvent& WXUNUSED(event)) {
  double ref;
  double dbDiv;
  choice_spe_ref->GetString(choice_spe_ref->GetSelection()).ToDouble(&ref);
  choice_spe_dbdiv->GetString(choice_spe_dbdiv->GetSelection()).ToDouble(&dbDiv);
  double lo = ref - 10 * dbDiv;
  window_1_spe->SetYRange(lo, ref, 0);
}

void MainFrame::OnSpanStart(wxCommandEvent& WXUNUSED(event)) {
  if (button_spe_start->GetValue()) {
    m_SMASpeLeft->SetNumRecords(m_SpeBufferLength >> 1);
    m_SMASpeRight->SetNumRecords(m_SpeBufferLength >> 1);
    button_spe_start->SetLabel(_T("停止 FFT"));
    m_RWAudio->StartSnd();
  } else {
    button_spe_start->SetLabel(_T("开始 FFT"));
    m_RWAudio->StopSnd();
  }
}

void MainFrame::OnGenStart(wxCommandEvent& WXUNUSED(event)) {
  if (button_gen_start->GetValue()) {
    button_gen_start->SetLabel(_T("Stop"));
    m_RWAudio->StartSnd();
  } else {
    button_gen_start->SetLabel(_T("Start"));
    m_RWAudio->StopSnd();
  }
  SendGenSettings();
}

void MainFrame::OnOscStart(wxCommandEvent& WXUNUSED(event)) {
  if (button_osc_start->GetValue()) {
    button_osc_start->SetLabel(_T("Stop"));
    m_RWAudio->StartSnd();
  } else {
    button_osc_start->SetLabel(_T("Start"));
    m_RWAudio->StopSnd();
  }
}

void MainFrame::OnFrmStart(wxCommandEvent& WXUNUSED(event)) {
  if (button_frm_start->GetValue()) {
    long ip;
    button_frm_start->SetLabel(_T("停止扫频"));
    wxString tpoints = text_ctrl1_frm->GetValue();
    tpoints.ToLong(&ip, 10);
    if (ip > 120) ip = 120;
    if (ip < 1) ip = 1;
    frm_ipoints = (int)ip;
    frm_istep = 0;

    frm_freqs.Clear();
    frm_lgains.Clear();
    frm_rgains.Clear();

    frm_measure = 0;
    frm_running = true;
    m_RWAudio->StartSnd();
  } else {
    frm_running = false;
    button_frm_start->SetValue(false);
    button_frm_start->SetLabel(_T("Start"));
    m_RWAudio->StopSnd();
    SendGenSettings();  // stop generator
  }
}

void MainFrame::OnGeneratorChanged(wxCommandEvent& WXUNUSED(event)) {
  if (checkbox_gen_sync->IsChecked()) {
    slide_r_fr->Enable(false);
    label_gen_wave_r->Enable(false);
    txt_freq_r->Enable(false);
    choice_r_wav->Enable(false);
    label_gen_freq_r->Enable(false);
  } else {
    slide_r_fr->Enable(true);
    choice_r_wav->Enable(true);
    txt_freq_r->Enable(true);
    label_gen_wave_r->Enable(true);
    label_gen_freq_r->Enable(true);
  }

  if (button_gen_start->GetValue()) {
    SendGenSettings();
  }
}

void MainFrame::OnOscChoiceChanged(wxCommandEvent& WXUNUSED(event)) {
  trigger_channel = choice_osc_trig_source->GetSelection();
  trigger_edge = (0 == choice_osc_trig_edge->GetSelection()) ? 1.0 : -1.0;
  TriggerSettings();
}

void MainFrame::OnOscScrollChanged(wxScrollEvent& WXUNUSED(event)) {
  wxString bla;
  trigger_level = slide_osc_level->GetValue() / 10.0;
  bla.Printf(wxT("Level: [-1.0...+1.0]: %2.1f"), trigger_level);
  label_osc_level->SetLabel(bla);
  TriggerSettings();
}

void MainFrame::OnGenScrollLChanged(wxScrollEvent& WXUNUSED(event)) {
  wxString bla;

  bla.Printf(wxT("%.1f"), floor(20.0 * pow(10.0, 3.0 * slide_l_fr->GetValue() / 200.0)));
  txt_freq_l->SetValue(bla);
  if (button_gen_start->GetValue()) {
    SendGenSettings();
  }
}

void MainFrame::OnGenScrollRChanged(wxScrollEvent& WXUNUSED(event)) {
  wxString bla;

  bla.Printf(wxT("%.1f"), floor(20.0 * pow(10.0, 3.0 * slide_r_fr->GetValue() / 200.0)));
  txt_freq_r->SetValue(bla);
  if (button_gen_start->GetValue()) {
    SendGenSettings();
  }
}

void MainFrame::OnGenScrollChanged(wxScrollEvent& WXUNUSED(event)) {
  wxString bla;

  bla.Printf(wxT("Amplitude: %d dB"), slide_l_am->GetValue());
  label_gen_ampl_l->SetLabel(bla);

  bla.Printf(wxT("Amplitude: %d dB"), slide_r_am->GetValue());
  label_gen_ampl_r->SetLabel(bla);

  if (button_gen_start->GetValue()) {
    SendGenSettings();
  }
}

void MainFrame::SendGenSettings() {
  float freq_l, freq_r;
  double phas2;
  double doubleToFreq;
  float gain_l, gain_r;

  if ((checkbox_l_en->IsChecked()) && (button_gen_start->GetValue())) {
    gain_l = 1.0 * pow(10, slide_l_am->GetValue() / 20.0);
  } else {
    gain_l = 0.0;
  }
  if ((checkbox_r_en->IsChecked()) && (button_gen_start->GetValue())) {
    gain_r = 1.0 * pow(10, slide_r_am->GetValue() / 20.0);
  } else {
    gain_r = 0.0;
  }

  text_gen_sync->GetValue().ToDouble(&phas2);

  txt_freq_l->GetValue().ToDouble(&doubleToFreq);
  freq_l = (float)doubleToFreq;

  txt_freq_r->GetValue().ToDouble(&doubleToFreq);
  freq_r = (float)doubleToFreq;

  RWAudio::Waveform shapeleft = static_cast<RWAudio::Waveform>(choice_l_wav->GetSelection());
  RWAudio::Waveform shaperight = static_cast<RWAudio::Waveform>(choice_r_wav->GetSelection());

  if (checkbox_gen_sync->IsChecked()) {
    freq_r = freq_l;
    shaperight = shapeleft;
  } else {
    phas2 = 0.0;
  }

  m_RWAudio->PlaySetGenerator(freq_l, freq_r, shapeleft, shaperight, gain_l, gain_r);
  m_RWAudio->PlaySetPhaseDiff(phas2 * 3.14159 / 180.0);  // should be in degrees now
}

void MainFrame::TriggerSettings() {
  auto tl = trigger_level * range_div;
  auto hl = 0.05 * range_div;
  if (trigger_channel == 2) {
    tl = trigger_level * range_div2;
    hl = 0.05 * range_div2;
  }
  m_RWAudio->SetTrigger(trigger_channel, trigger_edge, tl, hl, trigger_pre);
}

void MainFrame::OnSelectSndCard(wxCommandEvent& WXUNUSED(event)) {
  unsigned int recdev, pldev;
  RWAudioDevList playDevList;
  RWAudioDevList recordDevList;
  unsigned int newFrequency = m_SamplingFreq;
  AIStreamSettings m_StreamSettings;

  m_RWAudio->GetRWAudioDevices(&playDevList, &recordDevList);

  AudioInterfaceDialog dlg(this);

  m_StreamSettings.playDev = m_PlayDev;
  m_StreamSettings.recordDev = m_RecordDev;
  m_StreamSettings.freq = m_SamplingFreq;
  dlg.SetDevices(recordDevList, playDevList, m_StreamSettings);
  if (wxID_OK == dlg.ShowModal()) {
    // send settings to RWAudio
    dlg.GetSelectedDevs(&recdev, &pldev, &newFrequency);
    m_RWAudio->SetSndDevices(recdev, pldev, newFrequency);
    m_PlayDev = pldev;
    m_RecordDev = recdev;
    m_SamplingFreq = newFrequency;
    m_SMASpeLeft->SetNumRecords(m_SpeBufferLength >> 1);
    m_SMASpeRight->SetNumRecords(m_SpeBufferLength >> 1);
    setoscbuf();
    m_RWAudio->ChangeBufLen((unsigned long)(m_OscBufferLength), m_SpeBufferLength);
    g_OscBufferChanged.store(false);
    m_e4x4Detected = false;
    label_device_status->SetLabel(wxT("● 已手动选择音频接口"));
    label_device_status->SetForegroundColour(wxColour(91, 214, 141));
    label_device_detail->SetLabel(
        wxString::Format(wxT("录音设备 #%u · 播放设备 #%u · %u Hz"), m_RecordDev, m_PlayDev,
                         m_SamplingFreq));
  }
}

void MainFrame::OnTxtFreqLChanged(wxCommandEvent& WXUNUSED(event)) {
  if (button_gen_start->GetValue()) {
    SendGenSettings();
  }
}

void MainFrame::OnTxtFreqRChanged(wxCommandEvent& WXUNUSED(event)) {
  if (button_gen_start->GetValue()) {
    SendGenSettings();
  }
}

class AudMeSApp : public wxApp {
 public:
  virtual bool OnInit();
};

wxIMPLEMENT_APP(AudMeSApp);

bool AudMeSApp::OnInit() {
  wxInitAllImageHandlers();
  MainFrame* frame_1 = new MainFrame(NULL, wxID_ANY, wxT(""));
  SetTopWindow(frame_1);
  frame_1->Show();
  return true;
}
